server:
  port: 8888
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#  error:
#    whitelabel:
#      enabled: false

spring:
  application:
    name: food-luv-back

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#    open-in-view: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

#  mvc:
#    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false

# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용
# echo 'food-luv-backend-project-of-young-potato-spring-security-jwt-token-secret-key'|base64
jwt:
  secret: Zm9vZC1sdXYtYmFja2VuZC1wcm9qZWN0LW9mLXlvdW5nLXBvdGF0by1zcHJpbmctc2VjdXJpdHktand0LXRva2VuLXNlY3JldC1rZXk=
  access-token-validity-in-seconds: 1800000 # 30분
  refresh-token-validity-in-seconds: 604800000 # 7일

logging:
  level:
    root: INFO